### PR TITLE
io.js 3 / node 4 / nan 2.1 support (DONE)

### PR DESCRIPTION
**Pull request by unbornchikken**
Hi,

I'm opening up this PR, however it is not yet finished. Just for everyone to know that it is in progress.

Everything compiles except line https://github.com/unbornchikken/node-proxy/blob/master/src/node-proxy.cc#L1533. The issue is that nan 2 doesn't support SetCallAsFunctionHandler. I've opened up an issue: https://github.com/nodejs/nan/issues/427

If anyone has hope for this gets merged, please +1 that [nan issue above](https://github.com/nodejs/nan/issues/427).

### CODE REVIEW

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by unbornchikken** [comment]
We're still not there, NAN 2.1 is not released yet. :-1:

**Comment by unbornchikken** [comment]
So, the good news is NAN 2.1 released, so finally this PR gets done. All test passed on all Node.js versions including 4.x. I've also updated Travis stuff to do tests on Mac and Linux on the whole version range. All tests passed there of course. @samshull please merge and release this as soon as you can, because there are many who waits for this module update. Thanks for your hard work there anyway!

**Comment by marinintim** [comment]
:+1:

**Comment by samshull** [comment]
:+1: Great job! Thanks!

**Comment by samshull** [comment]
node-proxy@1.0.0

**Pull request merged**
